### ISSUE TITLE
move-to-go new myproject excel doesn't work

### ISSUE THREAD

**Issue by palsson** [Lundalogik/move-to-go#70]
Cant create a new project anymore

`move-to-go new myproject excel `

This has probably failed since nokogiri released version 1.8.0 in june 2017.

**Comment by palsson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [move-to-go new myproject excel doesn't work](https://trello.com/c/Pi4lteyF/1286-move-to-go-new-myproject-excel-doesnt-work)

**Comment by petterl** [comment]
I can reproduce this issue
